### ISSUE TITLE
Help needed implementing new build check to test PRs 

### ISSUE THREAD

**Issue by rohan472000** [rohan472000/rohan472000#10]
Issue Description:

I want to add a new build check to test PRs before merging. This will help to ensure that new codes do not break the existing functionality of the repository.

If you are interested to implement the build check, please raise a PR. 

Additional Information:

- The repository is written in Python.
- The build check should be run on every PR.
- The build check should fail if any wrong or incompatible code are added to 
   the README.md file and they break the existing functionality of the repository.

**Comment by rohan472000** [comment]
@Prikshit7766 Kindly check if it is working or not..

**Comment by Prikshit7766** [comment]
I think it is working

**Comment by rohan472000** [comment]
wait....why u included flake8....is it targeting PR or not???

**Comment by Prikshit7766** [comment]
> wait....why u included flake8....is it targeting PR or not???

I am using it for maintaining code consistency and readability in a project. Removing flake8 from the code will not affect the code itself.

**Comment by rohan472000** [comment]
Ok..but with it I also need to check whether this PR fetching meme or not updating readme or not....because if we merge any PR and then fetching and updating is not working , it will be mess.

**Comment by Prikshit7766** [comment]
To ensure that this PR doesn't disrupt the fetching and updating process, I've included comprehensive unit tests in `test_joke.py` and `test_readme.py`. These tests cover the functionality of fetching memes and updating the README file.

If there are any specific things you want me to test or any ideas you have, just let me know, and I'll tweak the tests accordingly!

**Comment by rohan472000** [comment]
See here
https://github.com/rohan472000/rohan472000/actions/runs/6380844266/job/17316029705

**Comment by Prikshit7766** [comment]
![image](https://github.com/rohan472000/rohan472000/assets/101416953/6d7eaec3-4bdd-4aa8-99b7-1e9dc0eff0ec)

The error message is a part of our test suite. In the `test_fetch_random_url_failure` test case, we intentionally simulate a request failure by raising a `RequestException`. This is done to verify that our code handles request failures correctly and returns `None`

**Comment by rohan472000** [comment]
So is it running unittest for both .py files under test folder?

**Comment by Prikshit7766** [comment]
> So is it running unittest for both .py files under test folder?

Yes

**Comment by rohan472000** [comment]
Ahh..thanks for clarification:)
