### ISSUE TITLE
Rohann Workflow

### ISSUE THREAD

**Issue by SilentJMA** [rohan472000/rohan472000#19]
Hi @rohan472000 can you setup a workflow for a repo of mine?

**Comment by rohan472000** [comment]
Yeah sure, in which repo and for what purpose you need workflow?

**Comment by SilentJMA** [comment]
@rohan472000  for similar repo doing the same job here it's called illustrate my readme

**Comment by rohan472000** [comment]
I didn't get you, can you explain?

**Comment by SilentJMA** [comment]
It's a repo who do the same job this repo do but instead of pulling memes it pull illustration

**Comment by rohan472000** [comment]
Ah got it..what Illustration you talking about exactly, can you show an example?

**Comment by SilentJMA** [comment]
[Here ](https://github.com/SilentJMA/Illustrate-My-README.md)@rohan472000

**Comment by rohan472000** [comment]
I am planning to create an executable version of the repository for easier installation via GitHub plugins. However, given the GPL license, it's essential that we maintain compliance. Your modifications to the code, while changing the data source, still retain the core logic, which might qualify as a derivative work under the GPL. 

Still my this project is incomplete, so I need collaboration, appreciate if you can collaborate.

**Comment by SilentJMA** [comment]
the one i'm doing i'm just checking there if it's working, when i made some progress i push to your repo like always

**Comment by rohan472000** [comment]
Oh ok...then you can copy that workflow from `.github/workflows`. As everything is same so it should pass.

**Comment by SilentJMA** [comment]
I don't want to break things for you while we are still experimenting.

**Comment by rohan472000** [comment]
Wait I'll raise a PR there in couple of days...as I'm traveling now so possibly tomorrow.

**Comment by SilentJMA** [comment]
ok i will close it until you are available

**Comment by rohan472000** [comment]
I can see it working on your readme.

**Comment by SilentJMA** [comment]
Yep i made it work yesterday it was something regarding the permission.
i will improve it later on...
