### ISSUE TITLE
Make this repo code executable to create a github plugins

### ISSUE THREAD

**Issue by rohan472000** [rohan472000/rohan472000#20]
I want to create an executable file that can be used as a plugin or action in other GitHub repositories. To create a GitHub Action that others can use in their repositories, we need to package it as a reusable action.

Feel free to discuss what you think and how it can be achieved, any PR to fulfill this request will be welcomed, but kindly discuss your thought before making PR.

**Comment by Mahkxai** [comment]
Hi - I have a few ideas for GH Actions:
1. Add a meme comment on every PR.
2. Trigger bot to add meme comment when using a specified keyword like '/meme'
3. Add a meme on PR reviews. 

Or something similar. 

For testing, I've incorporated No. 1 on [my fork](https://github.com/Mahkxai/GitHub-Meme-Generator) of this repo: a meme comment is added to every new PR. I can make a similar GitHub Action and package it to make it reusable in other repositories. Let me know what you think.

**Comment by rohan472000** [comment]
I didn't get your 1 and 2nd points usage but liked 3rd one....

By the way, main aim is make it executable, so that it can be used as plugins and work on any account.

**Comment by rohan472000** [comment]
Ahh...I see the first one it's good....can we have a set of memes specific on PRs..so whenever one makes a PR then they will get some memes on PR....not any random memes
.

**Comment by hrdkmishra** [comment]
last night i was trying to do it
what i did was created an action.yml in root and then make whole another repo that uses that action.yml but wasnt able to get by,
would love to contribute

**Comment by rohan472000** [comment]
Ya sure ...go ahead.
