### ISSUE TITLE
Implement User Notifications for README Updates

### ISSUE THREAD

**Issue by Swish78** [rohan472000/rohan472000#26]
I want to implement a feature that sends notifications whenever the README is updated with a new meme. This enhancement will be useful for notifying collaborators and followers about the latest meme content in the README.

**Comment by rohan472000** [comment]
Notification through what...mail or something else 


Also it will be annoying to members as meme fetched every 5 min....but I will be happy to see how you implement it , once merged then I disable the workflow but it will be there in repo.

**Comment by Swish78** [comment]
Notifications will be sent through email. 
I understand your concern about frequent fetching. I'll make sure the feature is easy to disable once merged, giving users control over notifications. I'm thinking about using smtplib for sending emails. Thank you for your feedback.

**Comment by ankitrajrj** [comment]
@rohan472000  i want to add some value in this repo . assign it to me

**Comment by rohan472000** [comment]
@ankitrajrj go ahead ...raise another issue,,,u will be assigned then raise PR...
