### ISSUE TITLE
fetch meme from cli via the current meme on readme!?

### ISSUE THREAD

**Issue by hrdkmishra** [rohan472000/rohan472000#45]
i have already coded this is okay?

**Comment by phase7** [comment]
@hrdkmishra link your PR so that we can see

**Comment by hrdkmishra** [comment]
Sure [this](https://github.com/hrdkmishra/fetch-readme-meme-cli)

**Comment by rohan472000** [comment]
This is form, not a PR.

**Comment by hrdkmishra** [comment]
mb here it is
https://github.com/rohan472000/rohan472000/pull/46

**Comment by hrdkmishra** [comment]
made the appropriate changes here is the new PR https://github.com/rohan472000/rohan472000/pull/68
