### ISSUE TITLE
Implementation of img tag in readme to display meme and use of beautifulsoup to update the readme file

### ISSUE THREAD

**Issue by prateiku** [rohan472000/rohan472000#48]
1. Instead of using a markdown in readme we can use an inline html `<img>` tag with an id attribute to improve the customization of Readme by giving the freedom to the user to modify it according to his style.
2. Using BeautifulSoup library which is intended to read and modify html it is possible to modify the `src ` attribute of the `img ` tag thus making sure there is no change in the other attributes in the tag.
3. Credit should be given to the author of the meme.

**Comment by rohan472000** [comment]
Raise PR.

**Comment by prateiku** [comment]
Done. Please have a look. [https://github.com/rohan472000/rohan472000/pull/49](https://github.com/rohan472000/rohan472000/pull/49
)
