### ISSUE TITLE
Add random meme generator with GUI and next meme button

### ISSUE THREAD

**Issue by animeshchaudhri** [rohan472000/rohan472000#60]
The application currently lacks a feature to generate random memes on demand. This feature would greatly improve the app by allowing users to view a stream of fresh, randomly generated memes.

## Proposed Solution:

- Create a "Random Meme" page in the app that displays a random meme on load.
- Add a "Next Meme" button that loads a new random meme when clicked.

**Comment by rohan472000** [comment]
Well appreciating your thoughts but this feature do the same, difference is just time, it fetches every 5min.

**Comment by animeshchaudhri** [comment]
Can i add a new file for the gui implementation to prevent conflicts @rohan472000 .
Please assign me the issue

**Comment by rohan472000** [comment]
Sure go ahead  :)

**Comment by animeshchaudhri** [comment]
Hey i have added the file please check it out ! I forgot to update the requirements.txt will do it right now

**Comment by animeshchaudhri** [comment]
# Preview:
![image](https://github.com/rohan472000/rohan472000/assets/111721851/07e4cb74-e7c0-4c09-b658-9e7da9eedf71)
